---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: yaude-boot-system
  name: yaude-boot-system
  namespace: yaude-icloud
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: svc
      k8s.kuboard.cn/name: yaude-boot-system
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/layer: svc
        k8s.kuboard.cn/name: yaude-boot-system
    spec:
      containers:
        - image: >-
            #APP_IMAGE_NAME
          imagePullPolicy: IfNotPresent
          name: yaude-boot-system
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/jvm: 'true'
    prometheus.io/port: '9999'
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: yaude-boot-system
  name: yaude-boot-system
  namespace: yaude-icloud
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: famrxx
      port: 8091
      protocol: TCP
      targetPort: 8091
    - name: exporter
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: yaude-boot-system
  sessionAffinity: None
  type: ClusterIP
