apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: yaude-icloud-java
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: yaude-icloud-java
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/buhuaqiang/yaude-icloud-java
      ref:
        branch: main
